### ISSUE TITLE
Integration with Radarr doesn't work

### ISSUE THREAD

**Issue by gruf23** [lingarr-translate/lingarr#22]
Hi,

I've configured Radarr integration and everything seems green and working, but I cant see my movies under "Movies" tab. It's just empty and refreshing cant help me.

<img width="486" alt="image" src="https://github.com/user-attachments/assets/5f006bc5-3f98-40eb-9d1f-15fd252c0487">

**Comment by rowanfuchs** [comment]
Usually, when movies aren't visible, the volume is incorrectly mapped. Currently, I've implemented a dynamic mapping, which seems to be prone to errors. I will refactor that before going to version 1.0. What is your Radarr mapping and Lingarr mapping?

**Comment by gruf23** [comment]
Yes, it might be the problem.
My movies volume for radarr container mapped as `/mnt/wd_black/media:/mnt/wd_black/media` and then specified to exact directory inside radarr config, but for lingarr is `/mnt/wd_black/media/movies:/app/media/movies`. Is there any way to change `app/media/movies` path in lingarr?

Similar mapping works for sonarr, though. Sonarr integration has different issue - shows are being added, but doesn't being deleted from lingarr. It doesnt recognize any subtitles, but I think it's my be issue on my side.

**Comment by rowanfuchs** [comment]
Alright, then I assume within Radarr you have a Root Folder of `/movies` under `Settings->Media Management->Root Folders`?
Could you have a look at the Lingarr container logs when opening the movies page, there should be a stacktrace that should be the final piece of the puzzle.

Series get added in any case, the failure there only occurs when opening a season so that's why you don't see any subtitles. It probably has the same issue.

Deletion only occurs after the next scheduled run of the show indexer.

**Comment by rowanfuchs** [comment]
I've dug into the deletion of shows and indeed there is an issue within the deletion. I've adjusted the code and in release 0.9.4 deletion will also work on shows.
